brimdata/brimcap

cli/analyzecli/display.go, cli/rootflags.go, cmd/brimcap/analyze/command.go, cmd/brimcap/index/command.go, cmd/brimcap/load/command.go, pcap/index.go, pcap/pcapio/error.go, pcap/pcapio/ngread.go, pcap/pcapio/reader.go, root.go
Brimcap load should create an index and a symlink to the processed pcap,
written the BRIMCAP_ROOT.
Closes #6
=> brimcap load: index pcap

cli/pcapsearchflags.go, cli/rootflags.go, cmd/brimcap/index/command.go, cmd/brimcap/launch/command.go, cmd/brimcap/main.go, cmd/brimcap/search/command.go, cmd/brimcap/slice/command.go, cmd/brimcap/ts/command.go, cmd/brimcap/ztests/search-duplicate.yaml, cmd/brimcap/ztests/search-notfound.yaml, cmd/brimcap/ztests/search.yaml, go.mod, go.sum, pcap/search.go, pcap/slicer.go, root.go
Add the brimcap launch command. brimcap launch takes as argument the time span,
protocol, source ip and port, and destination ip and port describing
a connection and searches through all the indexed pcaps in the BRIMCAP_ROOT
packets matching the description. If the search returns a result the packets
are opened in wireshark.
Additional changes:
- add brimcap search: the same thing as brimcap launch except it writes the
search result as a pcap file.
- brimcap index -root: If the -root flag is provided brimcap index will create
a index of the pcap in the BRIMCAP_ROOT.
Closes #7
=> Add brimcap launch command

analyzer/analyzer.go, analyzer/config.go, cmd/brimcap/ztests/analyze-process-error.yaml
Add workdir field to analyzer configuration. If workdir is set, the analyzer
process usees this directory as the current working directory for the executed
process.
Closes #16
=> Analyzer process: configurable working directory

.github/workflows/markdown-link-check-config.json, .github/workflows/markdown-link-check.yml
I've enabled these in our other repos that contain markdown docs so we don't have persistent dead links. Like the others, this is rigged up to run nightly and send its output to our internal Slack #docs channel so only people who want to be bothered by the failures have to see them.
I've already made the change so our org-level secret needed to send to Slack is available to the Brimcap repo, so this should be able to start running once it gets merged.
=> Add Actions for a markdown link checker

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
To help our users file good issues, I'm repurposing the templates we've been using for the Brim desktop app. Since these point at content from the Brimcap wiki, I'll hold off on merging it until after #30 gets merged.
=> Add GitHub Issue templates

.github/workflows/docs-publish.yml, README.md, docs/Home.md, docs/Troubleshooting.md, docs/_Footer.md, docs/_Sidebar.md
As the pcap/Zeek/Suricata-centric functionality migrates from the Brim app into Brimcap, docs regarding such functionality should likely move as well. A couple examples of wiki-bound items that are already in the queue are the move of the Zeek compatibility doc (brimdata/zed#2458) and a description of how the Suricata shaper works and could be customized (#8).
To make way for this, I'm replicating the approach we've used in the Brim repo where the original copy of the materials can live in a `docs/` directory in the main repo and we can use a GitHub Action that publishes its contents to the wiki mini-repo that lives off to its side. This way the revision history of the docs are kept with everything else.
To get the wiki started, I've repurposed some of the Troubleshooting content from the …
=> Add start of wiki & an Action to publish to it

.github/workflows/ci.yaml
If an advanced zed branch has been successfully merged to main, delete the
branch.
=> Delete successful advance zed branches

cmd/brimcap/analyze/command.go, cmd/brimcap/cut/command.go, cmd/brimcap/index/command.go, cmd/brimcap/info/command.go, cmd/brimcap/load/command.go, cmd/brimcap/main.go, cmd/brimcap/migrate/command.go, cmd/brimcap/root/command.go, cmd/brimcap/search/command.go, cmd/brimcap/slice/command.go, cmd/brimcap/ts/command.go, root.go
Add zqd migrate command for migrate old zqd spaces to zed lake pools. This is
a hidden command meant to be used specifically in the Brim desktop app for
migrating old zqd spaces, this is not meant for general consumption.
Closes #58
=> zqd migrate command

cmd/brimcap/migrate/command.go
This fixes the "The process cannot access the file because it is being used by
another process" error encountered when migrating on windows.
Closes #78
=> migrate: fix windows bug

cmd/brimcap/migrate/command.go
If an error occurs during an abort of a space migration, log the error
message.
=> brimcap migrate abort: error messages

cmd/brimcap/analyze/command.go, cmd/brimcap/cut/command.go, cmd/brimcap/index/command.go, cmd/brimcap/info/command.go, cmd/brimcap/load/command.go, cmd/brimcap/migrate/command.go, cmd/brimcap/root/command.go, cmd/brimcap/search/command.go, cmd/brimcap/slice/command.go, cmd/brimcap/ts/command.go
Add SIGTERM to the list of signals we listen to for graceful shutdown of
a brimcap command.
=> Graceful shutdown on sigterm

cmd/brimcap/migrate/command.go, go.mod
Let the invoker of brimcap migrate be responsible for deleting the
aborted space. Add pool_id to log messages to make this easier. Use
zap for logging.
=> brimcap migrate: keep aborted space

CHANGELOG.md
It's been a while since I've bundled a release artifact for Brimcap. Since we have beta users actively running Brimcap from the shell, I figure it'll be good to have a current artifact posted in case someone downloads from the repo rather than invoking the one in Brim's `zdeps/` directory.
Changes this covers:
https://github.com/brimdata/brimcap/compare/v0.0.3...6bde220
=> Changelog for v0.0.4

README.md
Now that the [https://github.com/brimdata/brimcap/wiki/Custom-Brimcap-Config](https://github.com/brimdata/brimcap/wiki/Custom-Brimcap-Config) article exists, I wanted to link to it from the README. At that point I noticed a bunch of other stuff that could stand to be updated, so here we have it!
(FWIW, my personal preference would be to capitalize "Brimcap" when speaking about the tool in the abstract and say `brimcap` in fixed-width lowercase when talking about invoking the command at the shell. However, it seems I'm often outvoted on these topics as we get down to the "tooling" layer, so I've attempted to go with the flow of what was there already.)
=> Brimcap README updates

cli/analyzecli/suricata.zed
When doing other shaper/typing work like brimdata/zed#2781 and brimdata/zed#2782, I've been making the change of using `this` to refer to the current record rather than the prior `.`, which made me realize this shaper could benefit from the same treatment.
=> Change "." to "this" in Suricata shaper

Makefile
brimdata/build-suricata#62 contains the backstory of why we've created an updated Suricata release artifact. I just tested it out on Arch Linux (the platform where #18 was first reported) by starting from an install of [https://storage.googleapis.com/brimsec-releases/brim/v0.25.0-prerelease-95581f92.0/linux/Brim-0.25.0-prerelease-95581f92.0.deb,](https://storage.googleapis.com/brimsec-releases/brim/v0.25.0-prerelease-95581f92.0/linux/Brim-0.25.0-prerelease-95581f92.0.deb,) reproducing the symptom reported in #18, then manually unpacking the [v5.0.3-brim2](https://github.com/brimdata/build-suricata/releases/tag/v5.0.3-brim2) artifact in place of the original one at the appropriate location under `/opt/Brim`, at which point I tested again and confirmed I could now successfully import pcaps …
=> Point to Suricata artifact v5.0.3-brim2

README.md, docs/Custom-Brimcap-Config.md, docs/Troubleshooting.md
This PR is part of the non-code coverage for #113.
Since the "a la carte" use of `brimcap analyze` and `brimcap index` already exists but just aren't used by the app yet, it was feasible for me to test and prep these updates in advance. Since it's written as if describing the current known behaviors of Brim, my intent is to hold off on merging this until we deliver the code changes expected in brimdata/brim#1716.
While I was in there, I corrected a couple other errors I spotted in the wiki articles and also added a couple analyzer caveats that @mattnibs recently shared with me. I adjusted the wording in a couple spots, so I'll add PR comments to highlight those and make sure they're confirmed before we commit.
=> Update Brimcap docs for phase-out of "brimcap load" (for merge with brim/1716)

cmd/brimcap/root/command.go
It looks like the tip from [https://github.com/brimdata/brimcap/pull/117#pullrequestreview-701368670](https://github.com/brimdata/brimcap/pull/117#pullrequestreview-701368670) got missed, so I've taken my stab at adjusting the help text. There were some links that needed adjusting also.
=> Purge brimcap load from help text, and fix links

analyzer/reader.go, cmd/brimcap/ztests/analyze-reader-error.yaml
Prepend warnings and errors generated by analyze readers with the
analyzer process that generated the records being read.
Closes #43
=> analyze: wrap reader warnings/errors

cli/analyzecli/display.go, cmd/brimcap/analyze/command.go, cmd/brimcap/root/command.go
Change the heuristic enabling json logging by default: If stdin, stdout and
stderr are all not terminals.
analyze stats output: If pretty status line output is enabled display
stats iff:
- -o is a file: display stats
- -o is stdout and stdout is NOT a terminal: display stats
Closes #118
=> Adjust output defaults

analyzer/reader.go, cmd/brimcap/ztests/analyze-bad-file.yaml, ztail/ztail.go, ztail/ztail_test.go
Previous ztail would error out if it encountered a file whose contents
anyio.Reader does not recognize. Instead have it issue a warning and
ignore the file.
Closes #119
=> ztail: Warn on bad file

CHANGELOG.md
@mattnibs noted that Brimcap has reached a level of functionality and stability that it seems appropriate to tag another release, and that we might as well make it `v1.0.0`. Having recently spent lots of time testing it while writing docs, plus just having done an audit of what open issues remain, I'm inclined to agree.
Here's an updated changelog with the final items before we build that artifact.
=> Changelog for v1.0.0

CHANGELOG.md
In the recent Brim beta refresh, I forgot to point at the latest Brimcap to take advantage of this bug fix (oops!) I'm seeking to rectify this by tagging a new release I'll point to in the _next_ Brim beta refresh.
=> Changelog for v1.0.1

cmd/brimcap/migrate/command.go
Since its possible that the data location for a space is not
zqdroot/sp_<space_id>, use SpaceRow.DataURI.
Closes brimdata/brim#1773
=> Migrate: use space DataURI

cmd/brimcap/root/command.go
brimdata/zed#3034 moved the contents of the former "Zed lake design doc" `design.md` to `README.md`. This PR fixes a link in the Brimcap CLI help that was pointing to the old location.
=> Fix link to Zed lake doc

docs/Custom-Brimcap-Config.md, examples/nfdump.yml, examples/zeek-suricata.yml
Recent changes on both the Brimcap and Zed sides have made the text of this article inaccurate. I've made changes here to make everything current and tested it on a scratch Linux VM. I'd like to get this merged before pushing the next beta Brim release so that way users can safely continue to follow the article.
I actually had to stop short of incorporating the last of the #148 changes I was interested in, as the lack of env var expansion cited in #151 makes it difficult to show the new `root:` setting in the example YAML in a portable way. However, this is not a showstopper, as it reads fine continuing to use the `-root` option at the shell for now.
=> Fix "Custom Brimcap Config" wiki article after brimcap/148 and Zed branch changes

CHANGELOG.md
So Brim can benefit from the fix in #153.
@mattnibs suggested we jump to `v1.1.0` per semver conventions since this introduces new functionality. I'm game!
=> Changelog for v1.1.0

package.json
We need to add the windows versions of the executables as well.
There may be a better way to do this with a node script that checks the environment and picks the proper binary. But this is the quick fix.
=> Windows too

docs/Custom-Brimcap-Config.md
In addition to the fixes in #235 that make the markdown link checker happy, I found this link in one of the wiki articles that's better pointing at the new Zed docs site.
=> Point link in wiki article to new Zed docs site

Makefile
This starts us using a Suricata artifact built on the `macos-11` Actions runner, per https://github.com/brimdata/build-suricata/pull/66. I don't expect functional changes from this. I just figure we might as well start getting off artifacts from the deprecated runners, since it'll help establish baseline stability in the event we do need to push builds with fixes in the future.
=> Point to Suricata artifact v5.0.3-brim4

queries.json
Looking back at the original Slack conversation that motivated #267, there was a decision to be made about whether the community user's input should lead us to replace the existing queries or add new ones. After some thought I chose the "add" option, since if there were quiet users that liked what was there before, they won't be left wondering what happened when they update to the new set.
I cleaned up some wording while I was in there to make the new & old ones make sense next to each other.
Here's example outputs for each query with the common "all.pcap" test data.
Closes #267
=> Add additional Suricata queries to library

.github/workflows/advance-zed.yaml, .github/workflows/markdown-link-check.yml
It was recently [announced](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) that the `set-output` syntax is being deprecated in Actions. I tested out the replacement syntax in a personal repo to get a feel for it and it works as described, so here's changes to our own Workflows to adopt the new approach.
=> Use replacement for deprecated set-output

.github/workflows/advance-zed.yaml, .github/workflows/ci.yaml
v2 is deprecated because it uses Node.js 12, which is no longer supported.
(inspired by https://github.com/brimdata/zed/pull/4185)
=> Upgrade to actions/checkout@v3 in CI

cmd/brimcap/ztests/analyze-combiner-error.yaml
This test occasionally fails because brimcap sometimes emits a line of stats output before exiting.  Add -nostats to prevent that.
See https://github.com/brimdata/brimcap/actions/runs/3472617729 for an example.
=> fix cmd/brimcap/ztests/analyze-combiner-error.yaml flakiness

README.md, go.mod, pcap/pcapio/read.go
Follow-up to the same upgrade in brimdata/zed#4219.
Changes to Go source files are from "gofmt -s -w .".
=> upgrade to Go 1.19

.github/workflows/advance-zed.yaml, .github/workflows/ci.yaml
Convert ci.yaml into a reusable workflow and call it from advance-zed.yaml.
=> simplify advance-zed.yaml and ci.yaml workflows

CHANGELOG.md
Since the last tagged Brimcap release, we've only had the single functional change documented here. However, we've not updated the Brimcap pointer in the Brim repo since August of 2022 and I'd prefer to have a GA tagged Brimcap shipped with Zui v1.0.0 for supportability reasons, so here's an updated changelog after which I'd tag a new release and point at it from the app repo.
https://github.com/brimdata/brimcap/compare/v1.2.0...40eafbc
=> Changelog for v1.3.0

.github/workflows/ci.yaml
Using github.sha as the ref in the checkout action prevents git from seeing the tag when a pushing a tag triggers the workflow, which in turn causes "brimcap -version" to report a SHA instead of the tag.  Fix by switching to github.ref.
=> check out github.ref in ci.yaml

.github/workflows/advance-zed.yaml
Pushing to main fails because of branch protection.  Bypass branch protection by using a personal access token with admin access.
=> bypass branch protection on main in advance-zed.yaml

CHANGELOG.md
I see no functional changes in Brimcap itself since we tagged v1.3.0 just a few weeks ago. However, since Brimcap uses Zed for shaping, there's a chance that a user could try to do some shaping and want to take advantage of some of the things we've already fixed/improved as called out in https://github.com/brimdata/zed/pull/4419. Therefore since we're about to put out the Zui v1.0 release I figure it's worth tagging an up-to-date Brimcap that we could point at, hence an update to the changelog.
https://github.com/brimdata/brimcap/compare/v1.3.0...ef96c35
=> Changelog for v1.4.0

Makefile
The updated Suricata artifact includes the change from https://github.com/brimdata/build-suricata/pull/69 which fixes https://github.com/brimdata/zui/issues/2715.
=> Point to Suricata artifact v5.0.3-brim5

package.json
This allows us to easily get the full path to the executable by running `yarn bin brimcap`
=> Add the binary to package.json

docs/Custom-Brimcap-Config.md, suricata.zed
In the days when the app was called Brim, there were presentation-layer overrides that made sure the leftmost column in the table output always showed the `ts` timestamp followed by `_path` & `event_type` tiles for Zeek & Suricata data in the second column, even though the underlying data had these fields in different orders.
Then a community user recently filed https://github.com/brimdata/zui/issues/2738 because we'd lost the Suricata tiles entirely in Zui. Here's how it looks with them restored after the fix to that issue in https://github.com/brimdata/zui/pull/2740 (Zui commit `f835e04`).
Perhaps the Zui plugin system might at some point in the future have some way to do the kinds of presentation-layer overrides, but for now, the change in this PR just tidies things up a little more by …
=> Put event_type before ts in Suricata shaper

Makefile, analyzer/processes.go, analyzer/processes_notwindows.go, analyzer/processes_windows.go, cmd/brimcap/ztests/analyze-bad-file.yaml, cmd/brimcap/ztests/analyze-combiner-error.yaml, cmd/brimcap/ztests/analyze-json-error.yaml, cmd/brimcap/ztests/analyze-process-error.yaml, cmd/brimcap/ztests/analyze-reader-error.yaml, cmd/brimcap/ztests/config-expand-env.yaml, cmd/brimcap/ztests/config-override.yaml, go.mod, go.sum, ztest_test.go
brimdata/zed#4581 changes the ztest package to run script-style ztests on Windows, but some of the ztests here don't run successfully on Windows.  Fix them by adjusting a few things.
* Upgrade Zed for brimdata/zed#4581 and brimdata/zed#4594.
* In Makefile, use ";" as path list separator on Windows instead of ":".
* In analyzer/processes.go, check for syscall.ERROR_BROKEN_PIPE on Windows instead of syscall.EPIPE.
* In ztests, adjust some outputs and paths and change analyzer commands to invoke Bash directly since Windows doesn't understand shebang lines (i.e., "#!/bin/bash").
* In ztest_test.go, use filepath.ToSlash for test names.  (Not strictly necessary, but it makes running individual tests easier.)
=> Fix ztests on Windows

analyzer/processes.go, analyzer/processes_notwindows.go, analyzer/processes_windows.go
Tests sometimes fail in CI due to this error.  Ignore it since it's no more interesting than ERROR_BROKEN_PIPE.
=> Ignore ERROR_NO_DATA on Windows in analyzer/processes.go

package.json
I figured this one out by running `yarn install --inline-builds` on Zui commit `cb746af` and `cd`'ing to the tmp directory it showed for where it cloned the Brimcap repo. By doing `git diff` while it was building I could see the following output:
```
$ git diff
diff --git a/package.json b/package.json
index ae2941c..aabe748 100644
--- a/package.json
+++ b/package.json
@@ -1,9 +1,7 @@
{
"name": "brimcap",
"version": "1.1.2",
-  "bin": {
-    "brimcap": "build/dist/brimcap"
-  },
+  "bin": "build/dist/brimcap",
"files": [
"build/dist/**"
],
```
So it looks like the changes from #306 to `package.json` are simplified during the build process and that's enough to render the build artifacts as "dirty".
Here's verification that the `-dirty` goes away when using the Brimcap based on this fix …
=> Adjust "bin" section of package.json

analyzer/processes.go
Like pipe errors, it's less interesting than the process error that caused it, and reporting it causes occasional failures for cmd/brimcap/ztests/analyze-process-error.yaml and
cmd/brimcap/ztests/analyze-combiner-error.yaml in CI.
=> Ignore fs.ErrClose in analyzer.runProcess

README.md
In a recent [community Slack thread](https://brimdata.slack.com/archives/C010DR0HHMF/p1700490455915979?thread_ts=1699776926.923289&cid=C010DR0HHMF) a user expressed confusion at not being able to follow the section of the Brimcap README for importing the saved queries. Indeed, when I tested this out for myself I realized that the recent [Preview & Load](https://zui.brimdata.io/docs/features/Preview-Load) enhancement has made it such that dragging a queries JSON into the app no longer populates the saved queries list. This experience was a good reminder that I should do a general video walk-through on Saved Queries as a feature. In the meantime, here I'm just proposing a short-term update to the Brimcap README to point users at the way for importing saved queries that still works ok.
=> Revise README section on "Brimcap Queries"

docs/Custom-Brimcap-Config.md
There once was a time when Zui's pull-down menu for changing app config was called **Preferences** on macOS and **Settings** on Windows/Linux. This led to it being referenced inconsistently in the docs. Between changes in https://github.com/brimdata/zui/pull/2866 and general macOS trends, we've now standardized on **Settings**, so here I'm fixing this Brimcap doc that still called it by the other.
=> Reference Settings, not Preferences

Makefile
The new Brimcap artifacts that use Zeek v6 have had over a week of use in tip-of-`main` Zui and Zui Insiders. That helped me spot & fix https://github.com/brimdata/zui/pull/2981, and [one user on community Slack](https://brimdata.slack.com/archives/C03MW6XT7HC/p1705775439374689) did report trying it out in Zui Insiders and reported a problem but they messaged me privately to follow up and it ended up being a repeat of what's fixed in #332. Therefore it feels like it's an appropriate time to just make it official.
=> Point to build-zeek artifact

analyzer/processes.go, cmd/brimcap/ztests/analyze-process-readall.yaml
This commit changes the behavior for analyzer processes so that processes that have successfully exited without reading all the data will continue to consume data from the byte stream insteading of returning an error and putting a stop to the copy goroutine.
Closes #331
=> analyzer: Have exited processes read all data

analyzer/combiner.go, analyzer/combiner_test.go, analyzer/reader.go
It's used only in this repository.  Move it here so system tests that exercise it can help us catch bugs caused by refactoring (like the one fixed in brimdata/zed#4712) sooner.
=> Import github.com/brimdata/zed/zio.Combiner

Makefile
This moves Brimcap (and hence will move Zui) to the latest Zeek for the reasons laid out in https://github.com/brimdata/build-zeek/pull/9.
=> Point to Zeek v6.2.0-brim1 artifact

Makefile
This moves Brimcap (and hence will move Zui) to the [Zeek v6.2.0-brim2 artifact](https://github.com/brimdata/build-zeek/releases/tag/v6.2.0-brim2) to take advantage of the enhancements described in those release notes.
=> Point to Zeek v6.2.0-brim2 artifact

.github/workflows/advance-zed.yaml, .github/workflows/ci.yaml, .github/workflows/docs-publish.yaml, .github/workflows/markdown-link-check.yaml
Node 16 actions are deprecated so upgrade to the Node 20 versions.
=> Upgrade Node 16 actions in .github/workflows

.github/workflows/ci.yaml
When attempting to generate a new Brimcap release, I noticed the generated Darwin one was for architecture `arm64` with none for `amd64` as we've always generated in the pass. I could see this happened because in the Actions workflow we've been pointing to the `-latest` revisions of the Runner types, but in the time since our last GA release, GitHub moved the `-latest` pointer forward to `macos-14` which is based on Apple silicon whereas `macos-12` and `macos-13` are still Intel-based.
I've avoided surprises like this in the Zui repo by pointing to explicit versions of the runners and only advancing them forward when those runner versions are deprecated or we have a specific motivation to advance the pointer and do the necessary testing at that time to ensure a smooth transition.
I …
=> Pin to specific versions of GitHub Actions Runners

docs/Troubleshooting.md
Since https://github.com/brimdata/zui/issues/1379 has been fixed, we no longer need to caution users about silent failures when clicking the **Packets** button. They'll actually see some kind of error message now, either from the OS, the app, or both.
=> Update Troubleshooting article to drop reference to fixed issue zui#1379

CHANGELOG.md
These are the customary CHANGELOG updates as part of a new set of GA releases, now with the release tag matching the dependent Zed release.
As previously mentioned in a team sync, having matching release tags helps in at least two ways:
1. It makes it easier for us to write content about new releases (i.e., no need to mention the separate version numbers for Zui, Brimcap, and Zed in our announcements on social media or the blog)
2. It makes it easier for users to feel confident that the Zed-dependent software like Zui/Brimcap are compatible with their Zed lakes/programsAPI/etc. by checking version strings and seeing they match.
I explicitly called out "major/minor version numbers" in the CHANGELOG to leave wiggle room for the possibility that we might do quick patch releases on any given …
=> Update CHANGELOG.md for v1.17.0

Makefile
This moves Brimcap (and hence will next move Zui) to the [Zeek v7.0.0-brim1 artifact](https://github.com/brimdata/build-zeek/releases/tag/v7.0.0-brim1).
=> Point to Zeek v7.0.0-brim1 artifact

analyzer/combiner.go, cli/pcapsearchflags.go, go.mod, go.sum, ztail/ztail.go
Go changes revert fc1c6e6f3da9cfda9a02e662f1b0554c0f8f267d to accomodate brimdata/zed#5278.
=> upgrade Zed to 427a57b70a954f990857c5190c44713b22d04ac8

.github/workflows/ci.yaml, docs/Troubleshooting.md
The link we'd been using previously has been giving HTTP 403 errors in the nightly link checker for a couple days now. Maybe that's a temporary problem, but on the assumption they just don't like being crawled or something we can use a different one.
=> Update 5-tuple link in Troubleshooting doc
