analyzer/analyzer.go
If analyze run encounters and error close the procChan. This fixes a bug where
if an error occurred before the process watch goroutine was launched, the
analyze cmd would deadlock waiting from analyze.Close to complete.
=> Fix error on analyze.run

.github/workflows/advance-zed.yaml, .github/workflows/ci.yaml
=> add auto advance zed functionality

README.md
I just installed brimcap and started getting familiar with it before integrating into the app. The readme was very helpful. These are just some suggestions I have. Take what you like!
=> Readme tweeks

cmd/brimcap/analyze/command.go, cmd/brimcap/index/command.go, cmd/brimcap/info/command.go, cmd/brimcap/launch/command.go, cmd/brimcap/load/command.go, cmd/brimcap/root/command.go, cmd/brimcap/search/command.go
=> Update command help information

cmd/brimcap/load/command.go, go.mod, go.sum
Adjust brimcap load to use endpoints in zed lake serve.
Depends on brimdata/zed#2629
Closes #62
=> brimcap load: use zed lake serve

root.go
=> Store pcap path as an absolute path

CHANGELOG.md
I'm looking to tag a new Brimcap release with intent to point at it from Brim so we can share the fix to #18 with one of the community users.
=> Changelog for v0.0.5

cli/analyzecli/display.go
Fix error where an analyze process that writes no records caused a
deadlock.
Closes #112
=> Fix no record deadlock

cli/analyzecli/display.go
Abbreviate bytes in status line and correct percentage calculation.
=> analyze: Fix status line percentage and bytes

CHANGELOG.md
I'm looking to tag a new Brimcap release so we can point Brim at it and do a beta refresh. Here's release notes.
=> Changelog for v0.0.6

cmd/brimcap/ztests/search-deleted.yaml, root.go
Ignore deleted file and remove index file.
=> pcap search: ignore deleted file

CHANGELOG.md
I'm planning to cut another release so I can point Brim at it and benefit from the fix in the next beta refresh.
=> Changelog for v1.0.2

cli/analyzecli/flags.go, cmd/brimcap/analyze/command.go, cmd/brimcap/ztests/analyze-delete-tmpdir.yaml
=> analyze: delete temp dirs when done

CHANGELOG.md
We'd like to tag a new Brimcap release to point Brim at so these improvements can go out in the next beta.
=> Changelog for v1.0.4

cmd/brimcap/ztests/config-expand-env.yaml, config.go
=> Allow env expansion in brimcap config yaml

CHANGELOG.md
So Brim can benefit from the fix in #156.
=> Changelog for v1.1.1

.github/workflows/ci.yaml
Really slowing things down, let's get rid of it.
=> Remove github cache step

README.md, pcap/pcapio/read.go
The Wireshark wiki has moved to a new home.
=> update Wireshark wiki links

package.json
We needed to make some changes so that the binaries get installed to the right places in the brim app.
=> Update package.json for usage with yarn version 2

.github/workflows/markdown-link-check.yml, README.md
Also switch markdown link checker to quiet mode.
=> Update dead lake link

cli/pcapsearchflags.go
As there are some difference between zson durations and go durations use package
zson to parse durations for the -duration flag.
=> pcap search flags: use zson to parse duration

README.md, queries.json
fixes https://github.com/brimdata/brim/issues/2431 and https://github.com/brimdata/brim/issues/2233
=> Add query lib and update readme

Makefile
Fixes #259
See these issues for details:
* https://github.com/brimdata/build-suricata/pull/63
* https://github.com/brimdata/build-suricata/pull/64
* https://github.com/brimdata/build-suricata/pull/65
=> Point to Suricata artifact v5.0.3-brim3

queries.json
Closes #268.
Here's an example of the query's output with the common "all.pcap" sample data.
=> Add "Top Queried Domains" to Zed query library

.github/workflows/advance-zed.yaml, .github/workflows/ci.yaml
This version lets us pull the Go version from go.mod, so do that.
=> update to actions/setup-go@v3 in CI

ztail/ztail.go
The goroutine created in Tailer.tailFile doesn't wait for Tailer.Read's caller to finish with a value before it reads the next one.  Since a zio.Reader retains ownership of the values it returns, reading the next value may overwrite a value still in use by Tailer.Read's caller.  Fix that by copying a value before sending on the results channel.
brimdata/zed#4188 triggers panics without this.
=> ztail: add missing copy in Tailer.tailFile

.github/workflows/ci.yaml, .github/workflows/docs-publish.yml, .github/workflows/markdown-link-check.yml
Node.js 12 actions are deprecated.
=> .github/workflows: upgrade Node.js 12 actions

CHANGELOG.md
https://github.com/brimdata/brimcap/compare/v1.4.0...75ce9bc
=> Changelog for v1.4.1

README.md, cmd/brimcap/ztests/analyze-process-error.yaml, go.mod
The change to cmd/brimcap/ztests/analyze-process-error.yaml is necessary
to make that test pass.
=> Upgrade to Go 1.20

CHANGELOG.md
https://github.com/brimdata/brimcap/compare/v1.5.2...c10c732
=> Changelog for v1.5.3

CHANGELOG.md
https://github.com/brimdata/brimcap/compare/v1.5.3...ccceb7b
=> Changelog for v1.5.4

CHANGELOG.md
https://github.com/brimdata/brimcap/compare/v1.5.4...1899577
=> Update CHANGELOG.md for v1.5.5

CHANGELOG.md
https://github.com/brimdata/brimcap/compare/v1.5.5...070d2a0
=> Changelog for v1.6.0

CHANGELOG.md
https://github.com/brimdata/brimcap/compare/v1.6.0...9b5db46
=> Update CHANGELOG.md for v1.7.0

analyzer/combiner.go, cli/pcapsearchflags.go, go.mod, go.sum, ztail/ztail.go
=> upgrade Zed to ce9626eb3c418f429de6e589af100ef5b2aa56e0

README.md
=> Update Zeek link on README.md

CHANGELOG.md
https://github.com/brimdata/brimcap/compare/v1.17.0...1fedc71
=> Update CHANGELOG.md for v1.18.0

README.md, go.mod
=> Upgrade to Go 1.23
